apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-gauge
spec:
  selector:
    matchLabels:
      app: target-gauge
  template:
    metadata:
      labels:
        app: target-gauge
    spec:
      containers:
      - name: target-gauge
        image: vmp-test-cn-beijing.cr.volces.com/vmp-test/target-gauge:latest
        #image: vmp-test-cn-guangzhou.cr.volces.com/vmp-test/target-gauge:latest
        #image: vmp-qa-cn-guilin-boe.cr.volces.com/target-gauge/target-gauge:latest
        resources:
          limits:
            memory: "30Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: target-gauge
  labels: 
    app: target-gauge
spec:
  selector:
    app: target-gauge
  type: ClusterIP
  ports:
  - name: target-gauge
    port: 8080
    targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: target-gauge-monitor
  labels:
    volcengine.vmp: 'true'
spec:
  selector:
    matchLabels:
      app: target-gauge
  endpoints:
    - port: target-gauge
      path: /metrics


